# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-10 08:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('block', '0002_auto_20170110_0714'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='block',
            name='btn',
        ),
        migrations.RemoveField(
            model_name='block',
            name='button',
        ),
        migrations.RemoveField(
            model_name='block',
            name='panel',
        ),
        migrations.AlterField(
            model_name='block',
            name='desc',
            field=models.CharField(max_length=100, verbose_name='版块描述'),
        ),
        migrations.AlterField(
            model_name='block',
            name='manager',
            field=models.CharField(max_length=100, verbose_name='版块管理员'),
        ),
        migrations.AlterField(
            model_name='block',
            name='name',
            field=models.CharField(max_length=100, verbose_name='版块名称'),
        ),
        migrations.AlterField(
            model_name='block',
            name='status',
            field=models.IntegerField(choices=[(0, '正常'), (-1, '删除')], default=0, verbose_name='版块状态'),
        ),
    ]
