# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-25 09:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('block', '0003_auto_20170110_0801'),
        ('article', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='block',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='block.Block', verbose_name='版块'),
            preserve_default=False,
        ),
    ]
